#!/bin/sh
#
# Automatically adds branch name and branch description to every commit message.
#
NAME=$(git rev-parse --abbrev-ref HEAD)
SOB=$(git var GIT_AUTHOR_IDENT | sed -n 's/^\(.*>\).*$/Signed-off-by: \1/p')
ORIGIN_MESSAGE=$(cat "$1")

echo "$NAME | $ORIGIN_MESSAGE" > "$1"
echo "" >> "$1"
echo "$SOB" >> "$1"
